# Opt in to new cops by default
AllCops:
  NewCops: enable

# Override the maximum line length
Layout/LineLength:
  Max: 160

# Allow the Podspec filename to match the project
Naming/FileName:
  Exclude:
    - 'WordPressKit.podspec'

Metrics/BlockLength:
  Exclude:
    - 'fastlane/Fastfile'
