// swift-tools-version:5.5

import PackageDescription

let package = Package(
    name: "WordPressKit",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "WordPressKit", targets: ["WordPressKit"])
    ],
    dependencies: [
//        .package(url: "https://github.com/buildkite/test-collector-swift", from: "0.3.0"),
//        .package(url: "https://github.com/AliSoftware/OHHTTPStubs", from: "9.1.0"),
//        // See https://github.com/erikdoe/ocmock/issues/500#issuecomment-1002700625
//        .package(url: "https://github.com/erikdoe/ocmock", revision: "afd2c6924e8a36cb872bc475248b978f743c6050"),
//        .package(url: "https://github.com/Quick/Quick", from: "6.0.0"),
        .package(url: "https://github.com/wordpress-mobile/NSObject-SafeExpectations", from: "0.0.6"),
        .package(url: "https://github.com/wordpress-mobile/WordPress-iOS-Shared", from: "2.0.0"),
        .package(url: "https://github.com/Alamofire/Alamofire", from: "4.0.0"),
        .package(url: "https://github.com/wordpress-mobile/wpxmlrpc", from: "0.9.0"),
        .package(url: "https://github.com/squarefrog/UIDeviceIdentifier", from: "2.2.0"),
    ],
    targets: [
        .target(
            name: "WordPressKitCore",
            dependencies: [
                "NSObject-SafeExpectations",
            ],
            path: ".",
            sources: [
                "WordPressKit/ObjectValidation.swift",
                "WordPressKit/NSCharacterSet+URLEncode.swift",
                "WordPressKit/RemoteReaderSiteInfoSubscription.swift",
                "WordPressKit/RemoteReaderSiteInfo.swift",
                "WordPressKit/RemotePostAutosave.swift",
                "WordPressKit/RemoteReaderCrossPostMeta.swift",
                "WordPressKit/RemoteReaderTopic.swift",
                "WordPressKit/RemoteMenu.swift",
                "WordPressKit/RemoteMenuItem.swift",
                "WordPressKit/RemoteUser+Likes.swift",
                "WordPressKit/RemoteReaderSite.swift",
                "WordPressKit/RemoteMenuLocation.swift",
                "WordPressKit/RemoteVideoPressVideo.swift",
                "WordPressKit/RemoteBlog.swift",
                "WordPressKit/RemoteBlogSettings.swift",
                "WordPressKit/RemoteBlogOptionsHelper.swift",
            ]
        ),
        .target(
            name: "WordPressKitObjC",
            dependencies: [
                "wpxmlrpc",
                "NSObject-SafeExpectations",
                "WordPressKitCore",
                .product(name: "WordPressShared", package: "WordPress-iOS-Shared"),
            ],
            path: ".",
            sources: [
                // find WordPressKit -name '*.m' -exec echo \"{}\", \;
                "WordPressKit/NSMutableDictionary+Helpers.m",
                "WordPressKit/RemotePostCategory.m",
                "WordPressKit/WordPressComServiceRemote.m",
                "WordPressKit/RemoteSourcePostAttribution.m",
                "WordPressKit/RemoteComment.m",
                "WordPressKit/PostServiceRemoteREST.m",
                "WordPressKit/TaxonomyServiceRemoteREST.m",
                "WordPressKit/MediaServiceRemoteREST.m",
                "WordPressKit/CommentServiceRemoteREST.m",
                "WordPressKit/ReaderSiteServiceRemote.m",
                "WordPressKit/PostServiceRemoteXMLRPC.m",
                "WordPressKit/BlogServiceRemoteXMLRPC.m",
                "WordPressKit/CommentServiceRemoteXMLRPC.m",
                "WordPressKit/ThemeServiceRemote.m",
                "WordPressKit/RemoteReaderPost.m",
                "WordPressKit/ReaderPostServiceRemote.m",
                "WordPressKit/MediaServiceRemoteXMLRPC.m",
                "WordPressKit/RemotePostType.m",
                "WordPressKit/NSDate+WordPressJSON.m",
                "WordPressKit/RemoteUser.m",
                "WordPressKit/ServiceRemoteWordPressComREST.m",
                "WordPressKit/SiteServiceRemoteWordPressComREST.m",
                "WordPressKit/RemotePostTag.m",
                "WordPressKit/BlogServiceRemoteREST.m",
                "WordPressKit/RemoteMedia.m",
                "WordPressKit/RemoteTaxonomyPaging.m",
                "WordPressKit/WPKitLogging.m",
                "WordPressKit/RemoteTheme.m",
                "WordPressKit/ReaderTopicServiceRemote.m",
                "WordPressKit/NSString+MD5.m",
                "WordPressKit/ServiceRemoteWordPressXMLRPC.m",
                "WordPressKit/RemotePost.m",
                "WordPressKit/AccountServiceRemoteREST.m",
                "WordPressKit/TaxonomyServiceRemoteXMLRPC.m",
                "WordPressKit/MenusServiceRemote.m",
            ],
            publicHeadersPath: "WordPressKit",
            cSettings: [.headerSearchPath("WordPressKit/Private")]
        ),
        .target(
            name: "WordPressKit",
            dependencies: [
                "Alamofire",
                "NSObject-SafeExpectations",
                "UIDeviceIdentifier",
                "WordPressKitCore",
                "WordPressKitObjC",
                .product(name: "WordPressShared", package: "WordPress-iOS-Shared"),
            ],
            path: ".",
            sources: [
                // find WordPressKit -name '*.swift' -exec echo \"{}\", \;
                "WordPressKit/FeatureFlagRemote.swift",
                "WordPressKit/RemoteSiteDesign.swift",
                "WordPressKit/RemoteDomain.swift",
                "WordPressKit/Insights/StatsDotComFollowersInsight.swift",
                "WordPressKit/Insights/StatsEmailFollowersInsight.swift",
                "WordPressKit/Insights/StatsAnnualAndMostPopularTimeInsight.swift",
                "WordPressKit/Insights/StatsAllTimesInsight.swift",
                "WordPressKit/Insights/StatsTodayInsight.swift",
                "WordPressKit/Insights/StatsPostingStreakInsight.swift",
                "WordPressKit/Insights/StatsPublicizeInsight.swift",
                "WordPressKit/Insights/StatsCommentsInsight.swift",
                "WordPressKit/Insights/StatsLastPostInsight.swift",
                "WordPressKit/Insights/StatsAllAnnualInsight.swift",
                "WordPressKit/Insights/StatsTagsAndCategoriesInsight.swift",
                "WordPressKit/WPState.swift",
                "WordPressKit/WordPressRestApi.swift",
                "WordPressKit/BlazeCampaign.swift",
                "WordPressKit/JetpackRestoreTypes.swift",
                "WordPressKit/EditorSettings.swift",
                "WordPressKit/NSMutableParagraphStyle+extensions.swift",
                "WordPressKit/RemoteGravatarProfile.swift",
                "WordPressKit/KeyringConnection.swift",
                "WordPressKit/AccountServiceRemoteREST+SocialService.swift",
                "WordPressKit/WebauthChallengeInfo.swift",
                "WordPressKit/RemoteDiff.swift",
                "WordPressKit/RemoteReaderPost.swift",
                "WordPressKit/RemoteNotificationSettings.swift",
                "WordPressKit/RemoteCommentV2.swift",
                "WordPressKit/Domains/DomainsServiceRemote.swift",
                "WordPressKit/Domains/DomainsServiceRemote+AllDomains.swift",
                "WordPressKit/ReaderTopicServiceRemote+Subscription.swift",
                "WordPressKit/ReaderPostServiceRemote+Subscriptions.swift",
                "WordPressKit/WordPressComRestApi.swift",
                "WordPressKit/StatsPostDetails.swift",
                "WordPressKit/QR Login/QRLoginServiceRemote.swift",
                "WordPressKit/QR Login/QRLoginValidationResponse.swift",
                "WordPressKit/WordPressOrgXMLRPCApi.swift",
                "WordPressKit/Enum+UnknownCaseRepresentable.swift",
                "WordPressKit/WordPressComServiceRemote+SiteSegments.swift",
                "WordPressKit/AutomatedTransferService.swift",
                "WordPressKit/SiteDesignServiceRemote.swift",
                "WordPressKit/WordPressComServiceRemote+SiteVerticalsPrompt.swift",
                "WordPressKit/RemotePageLayouts.swift",
                "WordPressKit/SocialLogin2FANonceInfo.swift",
                "WordPressKit/ServiceRequest.swift",
                "WordPressKit/ActivityServiceRemote_ApiVersion1_0.swift",
                "WordPressKit/RemotePublicizeService.swift",
                "WordPressKit/Plans/PlanServiceRemote.swift",
                "WordPressKit/Plans/PlanServiceRemote_ApiVersion1_3.swift",
                "WordPressKit/DashboardServiceRemote.swift",
                "WordPressKit/PluginDirectoryFeedPage.swift",
                "WordPressKit/PostServiceRemoteREST+Revisions.swift",
                "WordPressKit/HomepageSettingsServiceRemote.swift",
                "WordPressKit/EditorServiceRemote.swift",
                "WordPressKit/ReaderPostServiceRemote+RelatedPosts.swift",
                "WordPressKit/JetpackBackup.swift",
                "WordPressKit/NotificationSettingsServiceRemote.swift",
                "WordPressKit/PeopleServiceRemote.swift",
                "WordPressKit/GravatarServiceRemote.swift",
                "WordPressKit/BloggingPromptsServiceRemote.swift",
                "WordPressKit/RemoteHomepageType.swift",
                "WordPressKit/ReaderPostServiceRemote+Cards.swift",
                "WordPressKit/PluginServiceRemote.swift",
                "WordPressKit/PluginDirectoryServiceRemote.swift",
                "WordPressKit/Jetpack Scan/JetpackCredentials.swift",
                "WordPressKit/Jetpack Scan/JetpackThreatFixStatus.swift",
                "WordPressKit/Jetpack Scan/JetpackScanHistory.swift",
                "WordPressKit/Jetpack Scan/JetpackScan.swift",
                "WordPressKit/Jetpack Scan/JetpackScanThreat.swift",
                "WordPressKit/AtomicAuthenticationServiceRemote.swift",
                "WordPressKit/IPLocationRemote.swift",
                "WordPressKit/RemotePublicizeConnection.swift",
                "WordPressKit/RemoteNotification.swift",
                "WordPressKit/RemoteBloggingPrompt.swift",
                "WordPressKit/PluginState.swift",
                "WordPressKit/ReaderTopicServiceError.swift",
                "WordPressKit/HTTPAuthenticationAlertController.swift",
                "WordPressKit/RemoteShareAppContent.swift",
                "WordPressKit/AccountSettingsRemote.swift",
                "WordPressKit/TimeZoneServiceRemote.swift",
                "WordPressKit/Plugin Management/PluginManagementClient.swift",
                "WordPressKit/Plugin Management/JetpackPluginManagementClient.swift",
                "WordPressKit/Plugin Management/SelfHostedPluginManagementClient.swift",
                "WordPressKit/PushAuthenticationServiceRemote.swift",
                "WordPressKit/RemoteProfile.swift",
                "WordPressKit/JetpackBackupServiceRemote.swift",
                "WordPressKit/RemoteBloggingPromptsSettings.swift",
                "WordPressKit/RemoteBlogJetpackSettings.swift",
                "WordPressKit/CommentServiceRemoteREST+ApiV2.swift",
                "WordPressKit/WordPressRSDParser.swift",
                "WordPressKit/RemoteSharingButton.swift",
                "WordPressKit/NSAttributedString+extensions.swift",
                "WordPressKit/RemoteInviteLink.swift",
                "WordPressKit/ReaderSiteSearchServiceRemote.swift",
                "WordPressKit/Authenticator.swift",
                "WordPressKit/WPCountry.swift",
                "WordPressKit/BlazeServiceRemote.swift",
                "WordPressKit/DomainContactInformation.swift",
                "WordPressKit/RemotePublicizeInfo.swift",
                "WordPressKit/JSONDecoderExtension.swift",
                "WordPressKit/RemoteWpcomPlan.swift",
                "WordPressKit/WordPressOrgXMLRPCValidator.swift",
                "WordPressKit/ChecksumUtil.swift",
                "WordPressKit/RemoteReaderSimplePost.swift",
                "WordPressKit/ReaderFeed.swift",
                "WordPressKit/JetpackScanServiceRemote.swift",
                "WordPressKit/TransactionsServiceRemote.swift",
                "WordPressKit/BlockEditorSettingsServiceRemote.swift",
                "WordPressKit/ShareAppContentServiceRemote.swift",
                "WordPressKit/RemoteBlogJetpackMonitorSettings.swift",
                "WordPressKit/KeyringConnectionExternalUser.swift",
                "WordPressKit/JetpackSocialServiceRemote.swift",
                "WordPressKit/BlazeCampaignsSearchResponse.swift",
                "WordPressKit/FeatureFlag.swift",
                "WordPressKit/UsersServiceRemoteXMLRPC.swift",
                "WordPressKit/WordPressComServiceRemote+SiteVerticals.swift",
                "WordPressKit/JetpackServiceRemote.swift",
                "WordPressKit/WordPressOrgRestApi.swift",
                "WordPressKit/JetpackCapabilitiesServiceRemote.swift",
                "WordPressKit/RemoteBlogJetpackModulesSettings.swift",
                "WordPressKit/StatsServiceRemoteV2.swift",
                "WordPressKit/ReaderServiceDeliveryFrequency.swift",
                "WordPressKit/Date+endOfDay.swift",
                "WordPressKit/WPKitLogging.swift",
                "WordPressKit/Activity.swift",
                "WordPressKit/RemoteBlockEditorSettings.swift",
                "WordPressKit/SiteManagementServiceRemote.swift",
                "WordPressKit/PluginDirectoryEntry.swift",
                "WordPressKit/ActivityServiceRemote.swift",
                "WordPressKit/BlogJetpackSettingsServiceRemote.swift",
                "WordPressKit/JetpackProxyServiceRemote.swift",
                "WordPressKit/SitePluginCapabilities.swift",
                "WordPressKit/SitePlugin.swift",
                "WordPressKit/AnnouncementServiceRemote.swift",
                "WordPressKit/RemotePlan_ApiVersion1_3.swift",
                "WordPressKit/WordPressComServiceRemote+SiteCreation.swift",
                "WordPressKit/RemoteReaderInterest.swift",
                "WordPressKit/RemotePerson.swift",
                "WordPressKit/SharingServiceRemote.swift",
                "WordPressKit/PageLayoutServiceRemote.swift",
                "WordPressKit/WordPressComOAuthClient.swift",
                "WordPressKit/AutomatedTransferStatus.swift",
                "WordPressKit/Decodable+Dictionary.swift",
                "WordPressKit/ReaderTopicServiceRemote+Interests.swift",
                "WordPressKit/AccountSettings.swift",
                "WordPressKit/WPTimeZone.swift",
                "WordPressKit/ProductServiceRemote.swift",
                "WordPressKit/NotificationSyncServiceRemote.swift",
                "WordPressKit/RemoteReaderCard.swift",
                "WordPressKit/RemoteConfigRemote.swift",
                "WordPressKit/RemoteRevision.swift",
                "WordPressKit/ZendeskMetadata.swift",
                "WordPressKit/Time Interval/StatsTopAuthorsTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsSummaryTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsTopCountryTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsPublishedPostsTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsSearchTermTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsFileDownloadsTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsTopVideosTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsTopReferrersTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsTopClicksTimeIntervalData.swift",
                "WordPressKit/Time Interval/StatsTopPostsTimeIntervalData.swift",
                "WordPressKit/ReaderPostServiceRemote+V2.swift",
                "WordPressKit/Endpoint.swift",
                "WordPressKit/AppTransportSecuritySettings.swift",
            ]
        ),
        /*
        .testTarget(
            name: "WordPressKitTests",
            dependencies: [
                .target(name: "WordPressKit"),
                .product(name: "OCMock", package: "ocmock"),
                .product(name: "BuildkiteTestCollector", package: "test-collector-swift"),
                "Quick",
                "OHHTTPStubs",
            ]
        ),
        .testTarget(
            name: "WordPressKitObjCTests",
            dependencies: [
                .target(name: "WordPressKit"),
                .product(name: "OCMock", package: "ocmock"),
                .product(name: "BuildkiteTestCollector", package: "test-collector-swift"),
                "Quick",
                "OHHTTPStubs",
            ],
            resources: [.process("Resources")]
        ),
        */
    ]
)
