# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.1.0
  # Common environment values to use with the `env` key.
  env: &common_env
    # -v3 contains a workaround for a Simulator boot issue
    # See paaHJt-6gL-p2#comment-8712
    IMAGE_ID: xcode-15.3-v3

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: .buildkite/build-and-test.sh
    artifact_paths:
      - fastlane/test_output/*.xcresult.zip
      - fastlane/test_output/report.html
      - fastlane/test_output/report.junit
      - .build/derived-data/Logs/**/*.xcactivitylog
    env: *common_env
    plugins: *common_plugins

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validate Podspec"
    key: "validate"
    command: |
      validate_podspec --patch-cocoapods
    env: *common_env
    plugins: *common_plugins

  #################
  # Linters
  #################
  - label: ":swift: SwiftLint"
    command: run_swiftlint --strict
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "SwiftLint"
    agents:
      queue: "default"

  - label: "🧹 Lint"
    key: "lint"
    command: |
      lint_pod
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
