# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - automattic/bash-cache#2.8.0
  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-13.4.1

# This is the default pipeline – it will build and test the app
steps:
  - label: "🧹 Lint Source"
    key: "danger"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :cocoapods: Setting up Pods (will it work in the android queue?)"
      install_cocoapods

      echo "+++ Where did the Pods go? 🤔"
      ls

      echo "--- :rubocop: Check stuff via Danger"
      bundle exec danger --fail-on-errors=true
    plugins: *common_plugins
    agents:
      queue: android
