# frozen_string_literal: true

def super_long_method_to_trigger_rubocop_violation_super_long_method_to_trigger_rubocop_violation_super_long_method_to_trigger_rubocop_violation_super_long_method_to_trigger_rubocop_violation
  true
end

default_platform(:ios)

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'WordPressKit',
      prelaunch_simulator: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end
end
